version: '3.8'

services:
  gym-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    container_name: gym_website
