version: '3.8'

services:
  gym-frontend:
    container_name: gym-website
    build:
      context: .                # This specifies the build context (current directory)
      dockerfile: Dockerfile     # Specify the Dockerfile to build from
    ports:
      - "8081:80"               # Exposes port 8080 on your machine to port 80 in the container
    restart: unless-stopped     # Container will restart unless manually stopped
    volumes:
      - .:/usr/share/nginx/html # Optional: Mount local directory to container for live updates (if using Nginx for example)
